import os

SECRET_KEY = 'secret'
RECAPTCHA_PUBLIC_KEY = 'TEST'

FACEBOOK_TOKEN = "EAAG8ZCCEzUlEBAI5DiewsBvJrd3kADU8dCZAZBP6X5am7ZBrsV4G3pLIAnZACZAQSv8L6EHjiIPP2ZCdNhxmQ3hhSrVrNhUhMgskbMdkMtSnQyp9gfPhrFyuW1j12L5CZC2Pgc6sqNOjHT4OZBqXf4Mmr5sHOGnKCf1sCDKZCI0BUdFgZDZD"
VERIFY_TOKEN = "ebot messenger$$"

CASA_LINK = ""
SQLALCHEMY_DATABASE_URI = ""